using UnityEngine;

namespace JellyGate
{
    public static class GameLocalization
    {
        public const string PreferenceKey = "Toyfront.Language";
        public static GameLanguage Current { get; set; } = GameLanguage.Korean;
        public static bool English => Current == GameLanguage.English;
        public static string Text(string korean, string english) => English ? english : korean;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void InitializeBeforeFirstScene()
        {
            // The loading scene is the first visible frame. Resolve the persisted/system language
            // before any MonoBehaviour builds text so English devices never flash Korean first.
            Current = LoadInitialLanguage();
        }

        public static GameLanguage DefaultForSystemLanguage(SystemLanguage systemLanguage) =>
            systemLanguage == SystemLanguage.Korean ? GameLanguage.Korean : GameLanguage.English;

        public static GameLanguage LoadInitialLanguage()
        {
            if (PlayerPrefs.HasKey(PreferenceKey))
                return (GameLanguage)Mathf.Clamp(PlayerPrefs.GetInt(PreferenceKey),
                    (int)GameLanguage.Korean, (int)GameLanguage.English);
            var language = DefaultForSystemLanguage(Application.systemLanguage);
            PlayerPrefs.SetInt(PreferenceKey, (int)language);
            PlayerPrefs.Save();
            return language;
        }

        public static string Tier(AugmentTier tier) => English ? tier switch
        {
            AugmentTier.Bronze => "BRONZE",
            AugmentTier.Silver => "SILVER",
            AugmentTier.Gold => "GOLD",
            AugmentTier.Platinum => "PLATINUM",
            _ => "DIAMOND"
        } : tier switch
        {
            AugmentTier.Bronze => "브론즈",
            AugmentTier.Silver => "실버",
            AugmentTier.Gold => "골드",
            AugmentTier.Platinum => "플래티넘",
            _ => "다이아몬드"
        };

        public static string AugmentName(string key, string fallback)
        {
            if (English)
            {
                return key switch
                {
                    "TankDrill" => "Formation Basics",
                    "MeleeEdge" => "Dull Whetstone",
                    "RangedPractice" => "Practice Scope",
                    "MageFocus" => "Novice Mana Knot",
                    "SupportTriage" => "Emergency Hands",
                    "TankAnchor" => "Anchor Drill",
                    "MeleeMarch" => "Marching Step",
                    "RangedSpotter" => "Spotter Lens",
                    "MageConserve" => "Measured Casting",
                    "TankPlating" => "Layered Plating",
                    "MeleeTempo" => "Flowing Strikes",
                    "RangedRange" => "Long-range Calibration",
                    "MageRadius" => "Expanded Circle",
                    "SupportCooldown" => "Rapid Support",
                    "TankEscort" => "Escort Line",
                    "MeleePursuit" => "Pursuit Step",
                    "RangedFocus" => "Set the Sights",
                    "MagePrimer" => "Spell Primer",
                    "SupportRenewal" => "Renewing Hymn",
                    "FormationDiscipline" => "Combined-arms Drill",
                    "RoundRecovery" => "Survivor Relief Corps",
                    "MeleeShatter" => "Armor Shatter",
                    "RangedCrit" => "Weak-point Shot",
                    "MageOverload" => "Arcane Overload",
                    "SupportAura" => "Healing Echo",
                    "TankRally" => "Shield Rally",
                    "MeleeDuelist" => "Giant Duel",
                    "RangedMark" => "Hunter's Mark",
                    "MageBurn" => "Lingering Flame",
                    "SupportHaste" => "Quickening Chorus",
                    "TankAegis" => "Unyielding Shieldwall",
                    "MeleeCleave" => "Cyclone Slash",
                    "RangedRicochet" => "Ricochet Shot",
                    "MageEcho" => "Spell Reprise",
                    "SupportSanctuary" => "Starlight Sanctuary",
                    "TankBulwark" => "Living Bulwark",
                    "MeleeRelentless" => "Relentless Rhythm",
                    "RangedPierce" => "Piercing Line",
                    "MageResonance" => "Arcane Resonance",
                    "SupportRescue" => "Rescue Bell",
                    "TankUnbroken" => "Immovable Throne",
                    "MeleeExecution" => "Executioner's Oath",
                    "RangedBarrage" => "Tempest Volley",
                    "MageCataclysm" => "Cataclysm Circle",
                    "SupportAscension" => "Seraphic Command",
                    "TankCitadel" => "Last Citadel",
                    "MeleeOverdrive" => "Crimson Overdrive",
                    "RangedTempest" => "Tempest Battery",
                    "MageSingularity" => "Gravity Well",
                    "SupportMiracle" => "Miracle Procession",
                    "TankHealth" => "Reinforced Shield",
                    "RangedDamage" => "Sharpshooter Kit",
                    "SplashRadius" => "Starburst Lens",
                    "Budget" => "Coin Pouch",
                    "AttackSpeed" => "Pocket Spring",
                    "GateHeal" => "Quick Repair",
                    "TankArmor" => "Royal Plating",
                    "HillDamage" => "High Ground Training",
                    "HillGuard" => "Clifftop Guard",
                    "HillRange" => "Highland Scope",
                    "HillTempo" => "Summit Springs",
                    "HillDominion" => "Sky Dominion",
                    "DoubleShot" => "Twin Trigger",
                    "SplashDamage" => "Burst Formula",
                    "MagicDamage" => "Arcane Circuit",
                    "EnemySlow" => "Sticky Time",
                    "GateRepair" => "Guardian Seal",
                    "TankThorns" => "Spiked Guard",
                    "AllDamage" => "Frontline Order",
                    "Meteor" => "Comet Drop",
                    "LastStand" => "Last Stand",
                    "Duplicate" => "Copy Workshop",
                    "Fortress" => "Grand Formation",
                    "GateHealMajor" => "Emergency Rebuild",
                    "ActiveVolley" => "Royal Arrow Barrage",
                    "ActiveFreeze" => "Clock Stop",
                    "ActiveFortify" => "Field Repair",
                    "UnlockBombardier" => "Clockwork Contract",
                    "UnlockLancer" => "Dragonvein Contract",
                    "UnlockDruid" => "Grove Spirit Contract",
                    "UnlockMusketeer" => "Royal Musketeer Contract",
                    "UnlockOracle" => "Moon Oracle Contract",
                    _ => fallback
                };
            }

            return key switch
            {
                "TankDrill" => "기초 방진 훈련",
                "MeleeEdge" => "무딘 숫돌",
                "RangedPractice" => "연습용 조준경",
                "MageFocus" => "초급 마력 매듭",
                "SupportTriage" => "응급 손길",
                "TankAnchor" => "닻 내리기 훈련",
                "MeleeMarch" => "전진 보법",
                "RangedSpotter" => "관측 렌즈",
                "MageConserve" => "절제된 시전",
                "TankPlating" => "겹철판 갑주",
                "MeleeTempo" => "연속 베기 훈련",
                "RangedRange" => "정밀 장거리 조준",
                "MageRadius" => "확장 마법진",
                "SupportCooldown" => "신속한 지원",
                "TankEscort" => "호위 방진",
                "MeleePursuit" => "추격 보법",
                "RangedFocus" => "조준 고정",
                "MagePrimer" => "주문 예열",
                "SupportRenewal" => "회복의 찬가",
                "FormationDiscipline" => "병과 합동 훈련",
                "RoundRecovery" => "생존자 구호대",
                "MeleeShatter" => "갑옷 분쇄",
                "RangedCrit" => "약점 사격",
                "MageOverload" => "과부하 마법진",
                "SupportAura" => "치유의 메아리",
                "TankRally" => "방패 재정비",
                "MeleeDuelist" => "거인 결투",
                "RangedMark" => "사냥꾼의 표식",
                "MageBurn" => "잔류 마력",
                "SupportHaste" => "가속의 합창",
                "TankAegis" => "불굴의 방패벽",
                "MeleeCleave" => "회전 참격",
                "RangedRicochet" => "도탄 사격",
                "MageEcho" => "마법 재현",
                "SupportSanctuary" => "별빛 성역",
                "TankBulwark" => "살아 있는 방벽",
                "MeleeRelentless" => "불굴의 박자",
                "RangedPierce" => "관통 사선",
                "MageResonance" => "비전 공명",
                "SupportRescue" => "구조의 종",
                "TankUnbroken" => "움직이지 않는 왕좌",
                "MeleeExecution" => "처형자의 맹세",
                "RangedBarrage" => "폭풍 사격 진형",
                "MageCataclysm" => "대재앙 마법진",
                "SupportAscension" => "대천사의 지휘",
                "TankCitadel" => "최후의 성채",
                "MeleeOverdrive" => "진홍 과부하",
                "RangedTempest" => "폭풍 포대",
                "MageSingularity" => "중력 우물",
                "SupportMiracle" => "기적의 행렬",
                "TankHealth" => "강화 방패",
                "RangedDamage" => "정밀 조준 장비",
                "SplashRadius" => "성운 렌즈",
                "Budget" => "동전 주머니",
                "AttackSpeed" => "소형 태엽",
                "GateHeal" => "긴급 수리",
                "TankArmor" => "왕실 장갑",
                "HillDamage" => "고지 전투 훈련",
                "HillGuard" => "절벽 수비대",
                "HillRange" => "고지 조준경",
                "HillTempo" => "정상 태엽",
                "HillDominion" => "천공 지배",
                "DoubleShot" => "쌍발 방아쇠",
                "SplashDamage" => "폭발 공식",
                "MagicDamage" => "비전 회로",
                "EnemySlow" => "끈적한 시간",
                "GateRepair" => "수호 인장",
                "TankThorns" => "가시 방진",
                "AllDamage" => "전선 총동원령",
                "Meteor" => "혜성 낙하",
                "LastStand" => "최후의 방어선",
                "Duplicate" => "복제 인형 공방",
                "Fortress" => "대방진",
                "GateHealMajor" => "왕성 긴급 복구",
                "ActiveVolley" => "왕실 화살 포화",
                "ActiveFreeze" => "시간 고정",
                "ActiveFortify" => "현장 보수",
                "UnlockBombardier" => "시계태엽 계약",
                "UnlockLancer" => "용맥 창 계약",
                "UnlockDruid" => "숲의 정령 계약",
                "UnlockMusketeer" => "왕실 머스킷 계약",
                "UnlockOracle" => "달빛 예언 계약",
                _ => fallback
            };
        }

        public static string AugmentDescription(string key, float power, string fallback)
        {
            int P(float rate) => Mathf.RoundToInt(power * rate * 100f);
            int V(float rate) => Mathf.RoundToInt(power * rate);
            var slow = Mathf.RoundToInt((1f - 1f / (1f + power * .06f)) * 100f);

            if (English)
            {
                return key switch
                {
                    "TankDrill" => $"Tank damage +{P(.06f)}%, damage taken -{P(.035f)}%",
                    "MeleeEdge" => $"Melee damage +{P(.10f)}%",
                    "RangedPractice" => $"Ranged damage +{P(.10f)}%",
                    "MageFocus" => $"Mage damage +{P(.11f)}%",
                    "SupportTriage" => $"Support skills heal nearby allies for {P(.12f)}% of Magic",
                    "TankAnchor" => $"Holding tanks gain armor +{V(8f)}, resistance +{V(6f)}",
                    "MeleeMarch" => $"Melee movement speed +{P(.05f)}%",
                    "RangedSpotter" => $"Ranged detection range +{power * .28f:0.00}",
                    "MageConserve" => $"Mage skill cooldown -{P(.05f)}%",
                    "TankPlating" => $"Tank armor +{V(9f)}, resistance +{V(6f)}",
                    "MeleeTempo" => $"Melee attack speed +{P(.10f)}%",
                    "RangedRange" => $"Ranged attack range +{power * .20f:0.00}",
                    "MageRadius" => $"Mage effect radius +{power * .18f:0.00}",
                    "SupportCooldown" => $"Support skill cooldown -{P(.10f)}%",
                    "TankEscort" => $"Allies near a tank take {P(.04f)}% less damage",
                    "MeleePursuit" => $"Melee movement speed +{P(.06f)}%, detection +{power * .18f:0.00}",
                    "RangedFocus" => $"Holding ranged unit damage +{P(.08f)}%",
                    "MagePrimer" => $"Mage skill cooldown -{P(.08f)}%",
                    "SupportRenewal" => $"Support healing +{P(.18f)}% of Magic",
                    "FormationDiscipline" => $"All role damage +{P(.05f)}%",
                    "RoundRecovery" => $"After clearing a round, surviving units recover {P(.18f)}% max HP (30% cap)",
                    "MeleeShatter" => $"Melee hits reduce armor by {V(8f)} for 3.2 sec",
                    "RangedCrit" => $"Ranged critical chance +{P(.13f)}%, critical damage +{P(.24f)} pts (base 150%; stacks increase it)",
                    "MageOverload" => $"Mage damage +{P(.16f)}%, radius +{power * .14f:0.00}",
                    "SupportAura" => $"Support skills heal nearby allies for {P(.18f)}% of Magic",
                    "TankRally" => $"Tank skills restore about {Mathf.RoundToInt((.015f + power * .02f) * 100f)}% max HP",
                    "MeleeDuelist" => $"Melee damage to bosses +{P(.12f)}%",
                    "RangedMark" => $"Ranged critical chance +{P(.12f)}%",
                    "MageBurn" => $"Mage skills trigger delayed damage equal to {P(.12f)}% of Magic",
                    "SupportHaste" => $"Support skills advance nearby cooldowns by {.22f + power * .35f:0.00}s",
                    "TankAegis" => $"Tank damage taken -{P(.08f)}%",
                    "MeleeCleave" => $"Melee attacks cleave for {P(.32f)}% damage",
                    "RangedRicochet" => $"Ranged attacks ricochet for {P(.26f)}% damage",
                    "MageEcho" => $"Mage skills reprise after 0.28 sec for {P(.20f)}% of Magic",
                    "SupportSanctuary" => $"Support skills heal nearby allies for {P(.24f)}% of Magic",
                    "TankBulwark" => $"Allies near a tank take {P(.09f)}% less damage",
                    "MeleeRelentless" => $"Below 50% HP, melee attack speed +{P(.10f)}%",
                    "RangedPierce" => $"Ranged attacks transfer {P(.34f)}% damage to another target",
                    "MageResonance" => $"Mage radius +{power * .12f:0.00}, delayed damage {P(.14f)}% of Magic",
                    "SupportRescue" => $"Healing on allies below 35% HP +{P(.45f)}%",
                    "TankUnbroken" => $"Tank damage taken -{P(.10f)}%, armor +{V(10f)}, resistance +{V(8f)}",
                    "MeleeExecution" => $"Melee damage to enemies below 40% HP +{P(.22f)}%",
                    "RangedBarrage" => $"Ranged attack speed +{P(.10f)}%, range +{power * .11f:0.00}",
                    "MageCataclysm" => $"Mage damage +{P(.16f)}%, radius +{power * .16f:0.00}",
                    "SupportAscension" => $"Support cooldown -{P(.10f)}%, healing +{P(.26f)}% of Magic",
                    "TankCitadel" => $"Below 35% HP: damage taken -{P(.12f)}%, armor +{V(8f)}, resistance +{V(7f)}",
                    "MeleeOverdrive" => $"Below 50% HP: melee damage +{P(.10f)}%, speed +{P(.07f)}%",
                    "RangedTempest" => $"Ranged damage +{P(.05f)}%, speed +{P(.05f)}%, critical +{P(.06f)}%",
                    "MageSingularity" => $"Mage radius +{power * .08f:0.00}, delayed damage {P(.20f)}% of Magic",
                    "SupportMiracle" => $"Support cooldown -{P(.05f)}%, healing +{P(.28f)}% of Magic",
                    "TankHealth" => $"Shield unit max HP +{P(.12f)}%",
                    "RangedDamage" => $"Ranged basic damage +{P(.11f)}%",
                    "SplashRadius" => $"Area spell radius +{power * .16f:0.00}",
                    "Budget" => $"Coins at the start of every round +{V(4f)}",
                    "AttackSpeed" => $"All attack speed +{P(.05f)}%",
                    "GateHeal" => $"Restore gate +{Mathf.RoundToInt(38f + power * 18f)}",
                    "TankArmor" => $"Shield unit armor +{V(7f)}",
                    "HillDamage" => $"High-ground unit damage +{P(.09f)}%",
                    "HillGuard" => $"High-ground armor and resistance +{V(6f)}",
                    "HillRange" => $"High-ground attack range +{power * .16f:0.00}",
                    "HillTempo" => $"High-ground attack speed +{P(.06f)}%",
                    "HillDominion" => $"High-ground damage +{P(.07f)}%, range +{power * .08f:0.00}, defense +{V(6f)}",
                    "DoubleShot" => $"Ranged echo-shot damage {Mathf.RoundToInt(Mathf.Clamp(power * .14f, .08f, .42f) * 100f)}%",
                    "SplashDamage" => $"Area damage +{P(.1f)}%",
                    "MagicDamage" => $"Magic damage +{P(.1f)}%",
                    "EnemySlow" => $"Enemy speed -{slow}%",
                    "GateRepair" => $"Gate damage taken -{P(.075f)}%",
                    "TankThorns" => $"Tank counter damage +{V(9f)}",
                    "AllDamage" => $"All damage +{P(.07f)}%",
                    "Meteor" => $"Every {Mathf.Max(5.8f, 7.2f - power * .4f):0.0}s: {Mathf.RoundToInt(45f + power * 22f)} area magic damage",
                    "LastStand" => "Reduce the next 3 gate hits by 35%",
                    "Duplicate" => $"Placement copy chance {P(.035f)}%",
                    "Fortress" => "Shield defense and gate resilience up",
                    "GateHealMajor" => "Major gate restoration",
                    "ActiveVolley" => "[ACTIVE] Three arrow barrages strike separated enemy groups",
                    "ActiveFreeze" => "[ACTIVE] Fully freeze enemy movement and attacks",
                    "ActiveFortify" => "[ACTIVE] Repair and reinforce the gate",
                    "UnlockBombardier" => "Recruit the Clockwork Bombardier",
                    "UnlockLancer" => "Recruit the Dragonvein Lancer",
                    "UnlockDruid" => "Recruit the Grove Spiritcaller",
                    "UnlockMusketeer" => "Recruit the Royal Musketeer",
                    "UnlockOracle" => "Recruit the Moon Oracle",
                    _ => fallback
                };
            }

            return key switch
            {
                "TankDrill" => $"탱커 피해 +{P(.06f)}%, 받는 피해 -{P(.035f)}%",
                "MeleeEdge" => $"근접 유닛 피해 +{P(.10f)}%",
                "RangedPractice" => $"원거리 유닛 피해 +{P(.10f)}%",
                "MageFocus" => $"마법사 피해 +{P(.11f)}%",
                "SupportTriage" => $"서포터 스킬 사용 시 주변 아군을 마력의 {P(.12f)}%만큼 회복",
                "TankAnchor" => $"정지 명령 중인 탱커 방어력 +{V(8f)}, 마법 저항력 +{V(6f)}",
                "MeleeMarch" => $"근접 유닛 이동 속도 +{P(.05f)}%",
                "RangedSpotter" => $"원거리 유닛 탐지 범위 +{power * .28f:0.00}",
                "MageConserve" => $"마법사 스킬 재사용 대기시간 -{P(.05f)}%",
                "TankPlating" => $"탱커 방어력 +{V(9f)}, 마법 저항력 +{V(6f)}",
                "MeleeTempo" => $"근접 유닛 공격 속도 +{P(.10f)}%",
                "RangedRange" => $"원거리 유닛 사거리 +{power * .20f:0.00}",
                "MageRadius" => $"마법사 공격 범위 +{power * .18f:0.00}",
                "SupportCooldown" => $"서포터 스킬 재사용 대기시간 -{P(.10f)}%",
                "TankEscort" => $"탱커 가까이에 있는 아군이 받는 피해 -{P(.04f)}%",
                "MeleePursuit" => $"근접 이동 속도 +{P(.06f)}%, 탐지 범위 +{power * .18f:0.00}",
                "RangedFocus" => $"정지 명령 중인 원거리 유닛 피해 +{P(.08f)}%",
                "MagePrimer" => $"마법사 스킬 재사용 대기시간 -{P(.08f)}%",
                "SupportRenewal" => $"서포터 광역 회복량에 마력의 {P(.18f)}% 추가",
                "FormationDiscipline" => $"모든 병과 피해 +{P(.05f)}%",
                "RoundRecovery" => $"라운드 통과 시 생존 유닛 최대 체력의 {P(.18f)}% 회복 (최대 30%)",
                "MeleeShatter" => $"근접 공격이 3.2초간 적 방어력 -{V(8f)}",
                "RangedCrit" => $"원거리 치명타 확률 +{P(.13f)}%, 치명타 피해 +{P(.24f)}%p (기본 150%, 중첩 시 증가)",
                "MageOverload" => $"마법사 피해 +{P(.16f)}%, 공격 범위 +{power * .14f:0.00}",
                "SupportAura" => $"서포터 스킬 사용 시 주변 아군을 마력의 {P(.18f)}%만큼 회복",
                "TankRally" => $"탱커 스킬 사용 시 최대 체력의 약 {Mathf.RoundToInt((.015f + power * .02f) * 100f)}% 회복",
                "MeleeDuelist" => $"근접 유닛의 보스 대상 피해 +{P(.12f)}%",
                "RangedMark" => $"원거리 치명타 확률 +{P(.12f)}%",
                "MageBurn" => $"마법사 스킬이 마력의 {P(.12f)}% 지연 피해를 추가 발생",
                "SupportHaste" => $"서포터 스킬 사용 시 주변 아군 재사용 대기시간 {.22f + power * .35f:0.00}초 단축",
                "TankAegis" => $"탱커가 받는 피해 -{P(.08f)}%",
                "MeleeCleave" => $"근접 공격이 주변 적에게 원 피해의 {P(.32f)}% 확산",
                "RangedRicochet" => $"원거리 공격이 주변 적에게 원 피해의 {P(.26f)}% 도탄",
                "MageEcho" => $"마법사 스킬이 0.28초 후 마력의 {P(.20f)}% 피해로 재현",
                "SupportSanctuary" => $"서포터 스킬 사용 시 주변 아군을 마력의 {P(.24f)}%만큼 회복",
                "TankBulwark" => $"탱커 가까이에 있는 아군이 받는 피해 -{P(.09f)}%",
                "MeleeRelentless" => $"체력 50% 이하인 근접 유닛 공격 속도 +{P(.10f)}%",
                "RangedPierce" => $"원거리 공격 피해의 {P(.34f)}%를 다른 적에게 전달",
                "MageResonance" => $"마법 범위 +{power * .12f:0.00}, 마력의 {P(.14f)}% 지연 피해",
                "SupportRescue" => $"체력 35% 이하 아군이 받는 회복량 +{P(.45f)}%",
                "TankUnbroken" => $"탱커 받는 피해 -{P(.10f)}%, 방어력 +{V(10f)}, 마법 저항력 +{V(8f)}",
                "MeleeExecution" => $"근접 유닛이 체력 40% 이하 적에게 피해 +{P(.22f)}%",
                "RangedBarrage" => $"원거리 공격 속도 +{P(.10f)}%, 사거리 +{power * .11f:0.00}",
                "MageCataclysm" => $"마법사 피해 +{P(.16f)}%, 공격 범위 +{power * .16f:0.00}",
                "SupportAscension" => $"서포터 재사용 대기시간 -{P(.10f)}%, 광역 회복에 마력의 {P(.26f)}% 추가",
                "TankCitadel" => $"체력 35% 이하 탱커: 받는 피해 -{P(.12f)}%, 방어력 +{V(8f)}, 마법 저항력 +{V(7f)}",
                "MeleeOverdrive" => $"체력 50% 이하 근접 유닛: 피해 +{P(.10f)}%, 공격 속도 +{P(.07f)}%",
                "RangedTempest" => $"원거리 피해 +{P(.05f)}%, 공격 속도 +{P(.05f)}%, 치명타 +{P(.06f)}%",
                "MageSingularity" => $"마법 범위 +{power * .08f:0.00}, 마력의 {P(.20f)}% 지연 피해",
                "SupportMiracle" => $"서포터 재사용 대기시간 -{P(.05f)}%, 광역 회복에 마력의 {P(.28f)}% 추가",
                "TankHealth" => $"방패병 최대 체력 +{P(.12f)}%",
                "RangedDamage" => $"원거리 기본 공격 피해 +{P(.11f)}%",
                "SplashRadius" => $"범위 마법 효과 반경 +{power * .16f:0.00}",
                "Budget" => $"매 라운드 편성 코인 +{V(4f)}",
                "AttackSpeed" => $"모든 아군 공격 속도 +{P(.05f)}%",
                "GateHeal" => $"왕성 내구도 즉시 {Mathf.RoundToInt(38f + power * 18f)} 회복",
                "TankArmor" => $"방패병 방어력 +{V(7f)}",
                "HillDamage" => $"언덕 위 아군 피해 +{P(.09f)}%",
                "HillGuard" => $"언덕 위 아군 방어력·마법 저항 +{V(6f)}",
                "HillRange" => $"언덕 위 아군 사거리 +{power * .16f:0.00}",
                "HillTempo" => $"언덕 위 아군 공격 속도 +{P(.06f)}%",
                "HillDominion" => $"언덕 위 아군 피해 +{P(.07f)}%, 사거리 +{power * .08f:0.00}, 방어 +{V(6f)}",
                "DoubleShot" => $"원거리 추가 사격 피해 {Mathf.RoundToInt(Mathf.Clamp(power * .14f, .08f, .42f) * 100f)}%",
                "SplashDamage" => $"범위 공격 피해 +{P(.1f)}%",
                "MagicDamage" => $"마법 피해 +{P(.1f)}%",
                "EnemySlow" => $"적 이동 속도 -{slow}%",
                "GateRepair" => $"왕성이 받는 피해 -{P(.075f)}%",
                "TankThorns" => $"탱커 반격 피해 +{V(9f)}",
                "AllDamage" => $"모든 아군 피해 +{P(.07f)}%",
                "Meteor" => $"{Mathf.Max(5.8f, 7.2f - power * .4f):0.0}초마다 범위 마법 피해 {Mathf.RoundToInt(45f + power * 22f)}",
                "LastStand" => "성벽에 가해지는 다음 3회의 피해를 35% 줄입니다.",
                "Duplicate" => $"배치한 유닛 무료 복제 확률 {P(.035f)}%",
                "Fortress" => "방패병 방어와 왕성 피해 감소를 강화합니다.",
                "GateHealMajor" => "왕성 내구도를 크게 회복합니다.",
                "ActiveVolley" => "[액티브] 서로 떨어진 적 무리 최대 세 곳에 화살 포화를 내립니다.",
                "ActiveFreeze" => "[액티브] 모든 적의 이동과 공격을 완전히 정지합니다.",
                "ActiveFortify" => "[액티브] 왕성을 수리하고 임시 방벽을 세웁니다.",
                "UnlockBombardier" => "시계태엽 포병을 편입합니다.",
                "UnlockLancer" => "용맥 창기병을 편입합니다.",
                "UnlockDruid" => "숲의 정령술사를 편입합니다.",
                "UnlockMusketeer" => "왕실 머스킷병을 편입합니다.",
                "UnlockOracle" => "달빛 예언자를 편입합니다.",
                _ => fallback
            };
        }
    }
}
